name: Second Workflow
# on:
#     push:
#         branches: [main]
#         paths: ["src/**"]

# on:
#     pull_request:
#         branches: [main]

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Release version"
                required: true

jobs:
    JobA:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting message
              run: echo "Welcome Again to Github Action !"