name: Fifth Workflow
on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Show deploy message
              run: echo "Message:${{ secrets.DEPLOY_MESSAGE }}" 